import type { Provider } from './types'

export const defaultProviders: Provider[] = [
  {
    id: 'deepseek',
    displayName: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/anthropic',
    authEnvName: 'DEEPSEEK_API_KEY',
    mainModel: 'deepseek-v4-pro[1m]',
    fastModel: 'deepseek-v4-flash',
    opusModel: 'deepseek-v4-pro[1m]',
    sonnetModel: 'deepseek-v4-pro[1m]',
    haikuModel: 'deepseek-v4-flash',
    fableModel: 'deepseek-v4-pro[1m]',
    subagentModel: 'deepseek-v4-flash',
    effortLevel: 'max',
    autoCompactWindow: '',
    maxContextTokens: '',
    notes: 'Anthropic-compatible endpoint for Claude Code.',
    enabled: true,
    accent: 'green',
  },
  {
    id: 'kimi-global',
    displayName: 'Kimi Global',
    baseUrl: 'https://api.moonshot.ai/anthropic',
    authEnvName: 'KIMI_API_KEY',
    mainModel: 'kimi-k3',
    fastModel: 'kimi-k2.6',
    opusModel: 'kimi-k3',
    sonnetModel: 'kimi-k3',
    haikuModel: 'kimi-k2.6',
    fableModel: 'kimi-k3',
    subagentModel: 'kimi-k3',
    effortLevel: 'high',
    autoCompactWindow: '262144',
    maxContextTokens: '262144',
    notes: 'Moonshot global Anthropic-compatible endpoint.',
    enabled: true,
    accent: 'blue',
  },
  {
    id: 'kimi-code',
    displayName: 'Kimi Code',
    baseUrl: 'https://api.kimi.com/coding/',
    authEnvName: 'KIMI_API_KEY',
    mainModel: 'k3[1m]',
    fastModel: 'k3-256k',
    opusModel: 'k3[1m]',
    sonnetModel: 'k3[1m]',
    haikuModel: 'k3-256k',
    fableModel: 'k3[1m]',
    subagentModel: 'k3[1m]',
    effortLevel: 'high',
    autoCompactWindow: '1048576',
    maxContextTokens: '1048576',
    notes: 'Kimi Code K3 1M route. Requires an eligible membership tier.',
    enabled: true,
    accent: 'orange',
  },
]
